# Generated by Django 5.1.4 on 2025-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
